/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint confirming API availability.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trains
         * @description List scheduled trains with pagination.
         */
        get: operations["list_trains_api_trains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sections
         * @description List all railway track sections.
         */
        get: operations["list_sections_api_sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Maintenance Jobs
         * @description List maintenance jobs, with optional department filtering.
         */
        get: operations["list_maintenance_jobs_api_maintenance_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize Blocks
         * @description Run CP-SAT optimizer over pending maintenance jobs and persist block schedules.
         */
        post: operations["optimize_blocks_api_blocks_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Benchmark Report
         * @description Compare CP-SAT against FCFS and EDD baselines without mutating blocks (PRD Section 13).
         */
        get: operations["get_benchmark_report_api_blocks_benchmark_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/{id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain Block
         * @description Structured explainability for a scheduled maintenance block (FR6.1).
         */
        get: operations["explain_block_api_blocks__id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weekly Plan
         * @description 7-day rolling maintenance block plan (FR7.1).
         *
         *     Resolves already-scheduled blocks and optimization results across the coming 7 days.
         *     If no jobs have been scheduled yet, returns an empty list.
         */
        get: operations["get_weekly_plan_api_plans_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monthly Plan
         * @description 30-day maintenance block plan (FR7.2).
         *
         *     Resolves scheduled blocks across a 30-day planning window.
         *     Note: Simplified stand-in for true rolling-horizon planning, per PRD Section 7 (FR7.2) and Section 13 caveat.
         */
        get: operations["get_monthly_plan_api_plans_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Assignment
         * @description Result assignment for a single scheduled maintenance job.
         */
        Assignment: {
            /** Job Id */
            job_id: string;
            /** Section Id */
            section_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Conflict Count */
            conflict_count: number;
            /** Priority Score */
            priority_score: number;
            /** Window Rank */
            window_rank: number;
            /**
             * Relaxed
             * @default false
             */
            relaxed: boolean;
            /**
             * Hard Conflict
             * @default false
             */
            hard_conflict: boolean;
        };
        /**
         * BenchmarkComparison
         * @description Side-by-side performance metrics for FCFS, EDD, and CP-SAT.
         */
        BenchmarkComparison: {
            fcfs: components["schemas"]["ScheduleMetrics"];
            edd: components["schemas"]["ScheduleMetrics"];
            cpsat: components["schemas"]["ScheduleMetrics"];
        };
        /**
         * BenchmarkReport
         * @description Complete benchmarking report comparing heuristic baselines to CP-SAT.
         */
        BenchmarkReport: {
            /** Total Jobs */
            total_jobs: number;
            /** Reference Date */
            reference_date: string;
            metrics: components["schemas"]["BenchmarkComparison"];
            improvements: components["schemas"]["ImprovementMetrics"];
            /** Summary Statement */
            summary_statement: string;
            /**
             * Critical Delayed Jobs
             * @default []
             */
            critical_delayed_jobs: components["schemas"]["CriticalDelayDetail"][];
        };
        /**
         * BlockExplainOut
         * @description Structured explainability response for a scheduled block (FR6.1).
         */
        BlockExplainOut: {
            /** Block Id */
            block_id: string;
            /** Job Id */
            job_id: string;
            /** Section Id */
            section_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Status */
            status: string;
            /** Priority Score */
            priority_score: number;
            /** Priority Rank */
            priority_rank: number;
            /** Total Jobs */
            total_jobs: number;
            /** Conflict Count */
            conflict_count: number;
            /** Hard Conflict */
            hard_conflict: boolean;
            /** Relaxed */
            relaxed: boolean;
            /** Reason */
            reason: string;
        };
        /**
         * CriticalDelayDetail
         * @description Detailed audit information for a high-priority job delayed beyond 48h.
         */
        CriticalDelayDetail: {
            /** Job Id */
            job_id: string;
            /** Priority Score */
            priority_score: number;
            /** Section Id */
            section_id: string;
            /**
             * Earliest Candidate Start
             * Format: date-time
             */
            earliest_candidate_start: string;
            /**
             * Earliest Candidate End
             * Format: date-time
             */
            earliest_candidate_end: string;
            /** Earliest Candidate Conflicts */
            earliest_candidate_conflicts: number;
            /**
             * Assigned Start
             * Format: date-time
             */
            assigned_start: string;
            /**
             * Assigned End
             * Format: date-time
             */
            assigned_end: string;
            /** Assigned Conflicts */
            assigned_conflicts: number;
            /** Delay Hours */
            delay_hours: number;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImprovementMetrics
         * @description Relative improvement of CP-SAT over heuristic baselines.
         */
        ImprovementMetrics: {
            /** Conflict Reduction Vs Fcfs Pct */
            conflict_reduction_vs_fcfs_pct: number;
            /** Conflict Reduction Vs Edd Pct */
            conflict_reduction_vs_edd_pct: number;
            /** Critical Delay Reduction Vs Fcfs Pct */
            critical_delay_reduction_vs_fcfs_pct?: number | null;
            /** Critical Delay Reduction Vs Edd Pct */
            critical_delay_reduction_vs_edd_pct?: number | null;
            /** No Overlap Violations Prevented Vs Fcfs */
            no_overlap_violations_prevented_vs_fcfs: number;
            /** No Overlap Violations Prevented Vs Edd */
            no_overlap_violations_prevented_vs_edd: number;
        };
        /**
         * MaintenanceJobOut
         * @description Pydantic model for MaintenanceJob.
         */
        MaintenanceJobOut: {
            /** Job Id */
            job_id: string;
            /** Department */
            department: string;
            /** Asset Id */
            asset_id: string;
            /** Section Id */
            section_id: string;
            /** Defect Desc */
            defect_desc: string;
            /** Criticality */
            criticality: number;
            /** Urgency */
            urgency: number;
            /** Asset Risk */
            asset_risk: number;
            /** Overdue Factor */
            overdue_factor: number;
            /** Failure History */
            failure_history: number;
            /**
             * Priority Score
             * @default 0
             */
            priority_score: number | null;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Duration Min */
            duration_min: number;
            /** Day Night Pref */
            day_night_pref: string;
            /** Status */
            status: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Source Note */
            source_note: string;
            /**
             * Has Hard Conflict
             * @default false
             */
            has_hard_conflict: boolean;
        };
        /**
         * OptimizerRunSummary
         * @description Execution summary of an optimizer scheduling run with isolated conflict categories.
         */
        OptimizerRunSummary: {
            /** Jobs Scheduled */
            jobs_scheduled: number;
            /** Zero Conflict Jobs */
            zero_conflict_jobs: number;
            /** Relaxed But Clean Jobs */
            relaxed_but_clean_jobs: number;
            /** Hard Conflict Jobs */
            hard_conflict_jobs: number;
            /** Total Conflicts */
            total_conflicts: number;
            /** Assignments */
            assignments: components["schemas"]["Assignment"][];
        };
        /**
         * PlanItemOut
         * @description Single item in a multi-horizon rolling block plan.
         */
        PlanItemOut: {
            /** Block Id */
            block_id: string;
            /** Job Id */
            job_id: string;
            /** Section Id */
            section_id: string;
            /** Department */
            department: string;
            /** Priority Score */
            priority_score: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Duration Min */
            duration_min: number;
            /** Conflict Count */
            conflict_count: number;
            /** Status */
            status: string;
            /** Has Hard Conflict */
            has_hard_conflict: boolean;
            /** Reason */
            reason: string;
        };
        /**
         * ScheduleMetrics
         * @description Aggregate schedule quality metrics for a single scheduling algorithm.
         */
        ScheduleMetrics: {
            /** Algorithm */
            algorithm: string;
            /** Total Conflicts */
            total_conflicts: number;
            /** Conflicted Jobs Count */
            conflicted_jobs_count: number;
            /** Zero Conflict Jobs Count */
            zero_conflict_jobs_count: number;
            /** Critical Delayed Jobs Count */
            critical_delayed_jobs_count: number;
            /** Section No Overlap Violations */
            section_no_overlap_violations: number;
            /** Completion Spread Days */
            completion_spread_days: number;
        };
        /**
         * SectionOut
         * @description Pydantic model for Section.
         */
        SectionOut: {
            /** Section Id */
            section_id: string;
            /** Name */
            name: string;
            /** Single Line */
            single_line: boolean;
        };
        /**
         * TrainOut
         * @description Pydantic model for Train.
         */
        TrainOut: {
            /** Train Id */
            train_id: string;
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Destination */
            destination: string;
            /** Run Days */
            run_days: string;
            /** Stops */
            stops?: components["schemas"]["TrainStopOut"][] | null;
        };
        /**
         * TrainStopOut
         * @description Pydantic model for TrainStop.
         */
        TrainStopOut: {
            /** Id */
            id: number;
            /** Train Id */
            train_id: string;
            /** Station Code */
            station_code: string;
            /** Section Id */
            section_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Arrival
             * Format: date-time
             */
            arrival: string;
            /**
             * Departure
             * Format: date-time
             */
            departure: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_trains_api_trains_get: {
        parameters: {
            query?: {
                /** @description Number of records to skip */
                skip?: number;
                /** @description Max records to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sections_api_sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionOut"][];
                };
            };
        };
    };
    list_maintenance_jobs_api_maintenance_jobs_get: {
        parameters: {
            query?: {
                /** @description Filter by department: TMS, SMMS, or TDMS */
                department?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_blocks_api_blocks_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizerRunSummary"];
                };
            };
        };
    };
    get_benchmark_report_api_blocks_benchmark_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkReport"];
                };
            };
        };
    };
    explain_block_api_blocks__id__explain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockExplainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_plan_api_plans_weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItemOut"][];
                };
            };
        };
    };
    get_monthly_plan_api_plans_monthly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItemOut"][];
                };
            };
        };
    };
}
